/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAgentRegistry__factory } from "./IAgentRegistry__factory";
export { SimpleAgentRegistry__factory } from "./SimpleAgentRegistry__factory";
