/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAgentRegistry } from "./IAgentRegistry";
export type { SimpleAgentRegistry } from "./SimpleAgentRegistry";
export * as factories from "./factories";
export { IAgentRegistry__factory } from "./factories/IAgentRegistry__factory";
export { SimpleAgentRegistry__factory } from "./factories/SimpleAgentRegistry__factory";
